<a href="https://colab.research.google.com/github/ma22c041/ma22c041_2023_PL/blob/main/Assignment8/column_space.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from scipy.linalg import svd, qr
A = np.array([[1, -2, 3, -3], [2, -4, 9, -2], [-3, 6, -9, 9]])

In [ ]:
# Using QR factorization
Q, R = qr(A, mode='economic')
column_space_basis_qr = Q

print("Column Space Basis using QR:")
print(column_space_basis_qr)


Column Space Basis using QR:
[[-0.26726124  0.95618289 -0.11952286]
 [-0.53452248 -0.04390192  0.84401323]
 [ 0.80178373  0.28945968  0.52283453]]


In [ ]:
# Using SVD
U, s, VT = svd(A)
column_space_basis_svd = U

print("\nColumn Space Basis using SVD:")
print(column_space_basis_svd)



Column Space Basis using SVD:
[[ 2.66235859e-01  1.70641342e-01  9.48683298e-01]
 [ 5.39615303e-01 -8.41911709e-01 -5.55111512e-17]
 [-7.98707576e-01 -5.11924025e-01  3.16227766e-01]]


In [ ]:
# Task 2: Check if the column spaces obtained from QR and SVD are the same
column_space_dim_qr = np.linalg.matrix_rank(column_space_basis_qr)
column_space_dim_svd = np.linalg.matrix_rank(column_space_basis_svd)

if column_space_dim_qr == column_space_dim_svd:
    print("The column spaces obtained using QR and SVD are the same.")
else:
    print("The column spaces obtained using QR and SVD are not the same.")


The column spaces obtained using QR and SVD are the same.


In [ ]:
import numpy as np
from scipy.linalg import svd, qr
import time

# Create a random 500x500 matrix
random_matrix = np.random.rand(500, 500)

# Using QR factorization
start_time = time.time()
Q, R = qr(random_matrix, mode='economic')
qr_elapsed_time = time.time() - start_time

print(f"Time taken for QR factorization: {qr_elapsed_time} seconds")


Time taken for QR factorization: 0.03606915473937988 seconds


In [ ]:
import numpy as np
from scipy.linalg import svd, qr
import time

# Create a random 500x500 matrix
random_matrix = np.random.rand(500, 500)

# Using SVD
start_time = time.time()
U, s, VT = svd(random_matrix)
svd_elapsed_time = time.time() - start_time

print(f"Time taken for SVD: {svd_elapsed_time} seconds")


Time taken for SVD: 0.12517714500427246 seconds


In [ ]:
# SVD method is faster than QR factorization method