<a href="https://colab.research.google.com/github/ma22c041/ma22c041_2023_PL/blob/main/Assignment5/Row_swap.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

def swaprow(i, j, A):
    tmp = A[i, :]
    A[i, :] = A[j, :]
    A[j, :] = tmp


In [ ]:
import numpy as np

def swap_rows(i, j, A):
    A[[i, j]] = A[[j, i]] #  uses advanced NumPy indexing to directly swap rows i and j without the need for a temporary variable.


In [ ]:
                # correctness
# I've added the import statement import numpy as np to ensure NumPy is available for use in the function.
# I've changed the function name to swap_rows for better readability and adherence to Python naming conventions (snake_case).
# The line A[[i, j]] = A[[j, i]] uses advanced NumPy indexing to directly swap rows i and j without the need for a temporary variable.
# This is more efficient and concise than the original code.
# This improved code achieves the same functionality while being more efficient and concise.
                #efficiency
 #This is highly efficient because it leverages NumPy's optimized C-based operations,
 #resulting in faster execution compared to looping through elements in Python.
                # elegance
# The logic for swapping rows is more straightforward and clear.
#  the swapping is accomplished with a single line of code, which is more elegant.
                # brevity
# the improved code makes the reader to understand very quickly without need of much explaination


In [2]:
import numpy as np

def swaprow(i, j, A):
    if i != j and 0 <= i < A.shape[0] and 0 <= j < A.shape[0]:
        A[[i, j]] = A[[j, i]]
    else:
        print("indices are the same")

#  let us do this with an example of 3 * 3 matrices

# Create a sample NumPy array
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print("Original Array:")
print(A)

# Swap rows using the corrected swaprow function
swaprow(0, 2, A)
print("\nAfter swapping rows:")
print(A)

# Try to swap rows with invalid indices
swaprow(0, 0, A)

# Try to swap rows with out-of-bounds indices
swaprow(0, 3, A)


Original Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

After swapping rows:
[[7 8 9]
 [4 5 6]
 [1 2 3]]
indices are the same
indices are the same
