<a href="https://colab.research.google.com/github/ma22c041/ma22c041_2023_PL/blob/main/Assignment6/Pairwise_difference.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Generate a 1D numpy array with random values
x = np.random.rand(5)
print(x)

[0.14346045 0.52463863 0.60317155 0.48116283 0.55444353]


In [ ]:
import numpy as np

# Calculate the pairwise differences and store them in a 2D numpy array D
D = np.array([[xi - xj for xj in x] for xi in x])

# Print the resulting 2D array D
print(D)


[[ 0.         -0.38117818 -0.4597111  -0.33770238 -0.41098308]
 [ 0.38117818  0.         -0.07853292  0.0434758  -0.0298049 ]
 [ 0.4597111   0.07853292  0.          0.12200872  0.04872802]
 [ 0.33770238 -0.0434758  -0.12200872  0.         -0.0732807 ]
 [ 0.41098308  0.0298049  -0.04872802  0.0732807   0.        ]]
